{% set name = "symmeplot" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/symmeplot-{{ version }}.tar.gz
  sha256: 508b8a1a30e4bc753f4ee8f7bc975dce72a883c3dadf3e84c88fd5e4b39aba63

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - poetry-core
    - pip
  run:
    - python >=3.9.0
    - sympy >=1.12.0
    - numpy >=1.21.6
    - matplotlib-base >=3.7.0

test:
  imports:
    - symmeplot

about:
  home: https://github.com/tjstienstra/symmeplot
  summary: SymPy Mechanics Plotter
  description: |
    SymMePlot is a tool to visualize mechanical systems created using the mechanics
    module in SymPy, sympy.physics.mechanics. It utilitizes frontends like matplotlib
    or pyqtgraph to display the systems. SymMePlot is designed to be easy to use and
    flexible enough to handle a wide variety of systems.
  license: MIT
  license_file: LICENSE
  doc_url: https://tjstienstra.github.io/symmeplot/
  dev_url: https://github.com/tjstienstra/symmeplot

extra:
  recipe-maintainers:
    - tjstienstra
